Import the NumPy library and assign to the alias np.
Use the numpy.genfromtxt() function to read the nyc_taxis.csv file into NumPy. Assign the result to taxi.
Use the ndarray.shape attribute to assign the shape of taxi to taxi_shape.
Use the variable inspector under the code box to view the taxi ndarray and its shape after running your code.

In [2]:
# np.genfromtxt(filename, delimiter=None)
# data = np.genfromtxt('data.csv', delimiter=',') # In this case, because we have a CSV file, the delimiter is a comma

import numpy as np

taxi = np.genfromtxt("nyc_taxis.csv", delimiter = ",")

taxi_shape = taxi.shape

print(taxi.dtype)


float64


Use the numpy.genfromtxt() function to again read the nyc_taxis.csv file into NumPy, but this time, skip the first row. Assign the result to taxi.
Assign the shape of taxi to taxi_shape.
Use the variable inspector under the code box to view the taxi ndarray and its shape after you have run your code.


In [5]:
taxi = np.genfromtxt('nyc_taxis.csv', delimiter=',', skip_header=1)
taxi_shape = taxi.shape

print(taxi_shape)

(89560, 15)


Use vectorized boolean operations to:
Evaluate whether the elements in array a are less than 3. Assign the result to a_bool.
Evaluate whether the elements in array b are equal to "blue". Assign the result to b_bool.
Evaluate whether the elements in array c are greater than 100. Assign the result to c_bool.
Once you've run your code, use the variable inspector below the code box to view each boolean array.

In [8]:
a = np.array([1, 2, 3, 4, 5])
b = np.array(["blue", "blue", "red", "blue"])
c = np.array([80.0, 103.4, 96.9, 200.3])

a_bool = a < 3
b_bool = b == 'blue'
c_bool = c > 100



print(a_bool)
print(b_bool)
print(c_bool)

[ True  True False False False]
[ True  True False  True]
[False  True False  True]


Calculate the number of rides in the taxi ndarray that are from February:
Create a boolean array, february_bool, that evaluates whether the items in pickup_month are equal to 2.
Use the february_bool boolean array to index pickup_month. Assign the result to february.
Use the ndarray.shape attribute to find the number of items in february. Assign the result to february_rides.
Once you have run your code, use the variable inspector to view the number of rides for February.

In [9]:
pickup_month = taxi[:,1]

january_bool = pickup_month == 1
january = pickup_month[january_bool]
january_rides = january.shape[0]

february_bool = pickup_month == 2
february = pickup_month[february_bool]
february_rides = february.shape[0]


#R feb_bool <- taxi$pickup_month == 2
#R output <- taxi$pickup_month[feb_bool]

#R output1 <- taxi$pickup_month[taxi$pickup_month==2]



Create a boolean array, tip_bool, that determines which rows have values for the tip_amount column of more than 50.
Use the tip_bool array to select all rows from taxi with values tip amounts of more than 50, and the columns from indexes 5 to 13 inclusive. Assign the resulting array to top_tips.

In [10]:
tip_amount = taxi[:,12]

tip_bool = tip_amount > 50
top_tips = taxi[tip_bool,5:14]

In [12]:
# this creates a copy of our taxi ndarray
taxi_modified = taxi.copy()

taxi_modified[28214,5] = 1
taxi_modified[:,0] = 16
taxi_modified[1800:1802,7] = taxi_modified[:,7].mean()

We again used the ndarray.copy() method to make taxi_copy, a copy of our original for this exercise.

Select the fourteenth column (index 13) in taxi_copy. Assign it to a variable named total_amount.
For rows where the value of total_amount is less than 0, use assignment to change the value to 0.

In [19]:
# this creates a copy of our taxi ndarray
taxi_copy = taxi.copy()
total_amount = taxi_copy[:,13]
total_amount[total_amount < 0] = 0

We have created a new copy of our taxi dataset, taxi_modified with an additional column containing the value 0 for every row.

In our new column at index 15, assign the value 1 if the pickup_location_code (column index 5) corresponds to an airport location, leaving the value as 0 otherwise by performing these three operations:
For rows where the value for the column index 5 is equal to 2 (JFK Airport), assign the value 1 to column index 15.
For rows where the value for the column index 5 is equal to 3 (LaGuardia Airport), assign the value 1 to column index 15.
For rows where the value for the column index 5 is equal to 5 (Newark Airport), assign the value 1 to column index 15.

In [24]:
# create a new column filled with `0`.
zeros = np.zeros([taxi.shape[0], 1])
taxi_modified = np.concatenate([taxi, zeros], axis=1)
print(taxi_modified)

# array[array[:, column_for_COMPARISON] == value_for_COMPARISON, column_for_ASSIGNMENT OF NEW VALUE] = new_value

taxi_modified[taxi_modified[:,5] == 2, 15] = 1
taxi_modified[taxi_modified[:,5] == 3, 15] = 1
taxi_modified[taxi_modified[:,5] == 5, 15] = 1

[[2.016e+03 1.000e+00 1.000e+00 ... 6.999e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 5.430e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 3.780e+01 2.000e+00 0.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 6.334e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 4.475e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.484e+01 2.000e+00 0.000e+00]]


Using the original taxi ndarray, calculate how many trips had JFK Airport as their destination:
Use boolean indexing to select only the rows where the dropoff_location_code column (column index 6) has a value that corresponds to JFK. Assign the result to jfk.
Calculate how many rows are in the new jfk array and assign the result to jfk_count.
Calculate how many trips from taxi had Laguardia Airport as their destination:
Use boolean indexing to select only the rows where the dropoff_location_code column (column index 6) has a value that corresponds to Laguardia. Assign the result to laguardia.
Calculate how many rows are in the new laguardia array. Assign the result to laguardia_count.
Calculate how many trips from taxi had Newark Airport as their destination:
Select only the rows where the dropoff_location_code column has a value that corresponds to Newark, and assign the result to newark.
Calculate how many rows are in the new newark array and assign the result to newark_count.
After you have run your code, inspect the values for jfk_count, laguardia_count, and newark_count and see which airport has the most dropoffs.

In [29]:
jfk = taxi[taxi[:,6] == 2, 6]
jfk_count = len(jfk)

laguardia = taxi[taxi[:,6] == 3]
laguardia_count = len(laguardia)

newark = taxi[taxi[:,6] == 5, 6]
newark_count = len(newark)

print(jfk_count)
print(laguardia_count)
print(newark_count)

11832
16602
63


In [31]:
jfk = taxi[taxi[:,6] == 2]
jfk_count = jfk.shape[0]

laguardia = taxi[taxi[:,6] == 3]
laguardia_count = laguardia.shape[0]

newark = taxi[taxi[:,6] == 5]
newark_count = newark.shape[0]

print(jfk_count)
print(laguardia_count)
print(newark_count)

11832
16602
63


In [36]:
trip_mph = taxi[:,7] / (taxi[:,8] / 3600)
cleaned_taxi = taxi[trip_mph < 100]

mean_distance = cleaned_taxi[:,7].mean()
mean_length = cleaned_taxi[:,8].mean()
mean_total_amount = cleaned_taxi[:,13].mean()